### ISSUE TITLE
Error - Unknown function: textobj#user#plugin

### ISSUE THREAD

**Issue by joech4n** [mattn/vim-textobj-url#5]
Hi there, thanks for creating this plugin. Any ideas why I may be getting this error upon vim start?

    ❯ /usr/local/bin/vim
    Error detected while processing /Users/username/.dotfiles/vim/vim.symlink/plugins/.dein/plugin/textobj/url.vim:
    line   10:
    E117: Unknown function: textobj#user#plugin
    Press ENTER or type command to continue

    ❯ /usr/local/bin/vim --version
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  9 2016 12:21:10)
    MacOS X (unix) version
    Included patches: 1-71
    Compiled by Homebrew
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +file_in_path    +mouse_sgr       +tag_old_static
    +arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
    +autocmd         +float           +mouse_urxvt     -tcl
    -balloon_eval    +folding         +mouse_xterm     +termguicolors
    -browse          -footer          +multi_byte      +terminfo
    ++builtin_terms  +fork()          +multi_lang      +termresponse
    +byte_offset     -gettext         -mzscheme        +textobjects
    +channel         -hangul_input    +netbeans_intg   +timers
    +cindent         +iconv           +num64           +title
    -clientserver    +insert_expand   +packages        -toolbar
    +clipboard       +job             +path_extra      +user_commands
    +cmdline_compl   +jumplist        +perl            +vertsplit
    +cmdline_hist    +keymap          +persistent_undo +virtualedit
    +cmdline_info    +lambda          +postscript      +visual
    +comments        +langmap         +printer         +visualextra
    +conceal         +libcall         +profile         +viminfo
    +cryptv          +linebreak       +python          +vreplace
    +cscope          +lispindent      -python3         +wildignore
    +cursorbind      +listcmds        +quickfix        +wildmenu
    +cursorshape     +localmap        +reltime         +windows
    +dialog_con      -lua             +rightleft       +writebackup
    +diff            +menu            +ruby            -X11
    +digraphs        +mksession       +scrollbind      -xfontset
    -dnd             +modify_fname    +signs           -xim
    -ebcdic          +mouse           +smartindent     -xpm
    +emacs_tags      -mouseshape      +startuptime     -xsmp
    +eval            +mouse_dec       +statusline      -xterm_clipboard
    +ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
    +extra_search    -mouse_jsbterm   +syntax
    +farsi           +mouse_netterm   +tag_binary
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: clang   -L. -L/usr/local/lib  -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc

**Comment by mattn** [comment]
please install https://github.com/kana/vim-textobj-user

**Comment by joech4n** [comment]
That did the trick, thanks @mattn!
